/*
 * SelectIP.java
 *
 * Created on 07 أكتوبر, 2009, 04:04 م
 */

package network;

/**
 * 
 * @author compio palace
 */
@SuppressWarnings("serial")
public class SelectIP extends javax.swing.JFrame {
	String myStr = null;
	public static int[] localIP = new int[4];

	/** Creates new form SelectIP */
	public SelectIP() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jButton1.setText("jButton1");
		getContentPane().add(jButton1);
		jButton1.setBounds(210, 210, 73, 23);

		jList1
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						jList1ValueChanged(evt);
					}
				});
		jScrollPane1.setViewportView(jList1);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(290, 50, 258, 130);

		jLabel1.setText("jLabel1");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(0, 0, 400, 300);

		pack();
	}

	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {
		String[] temp = myStr.split("[.]");

		for (int i = 0; i < temp.length; i++) {
			int Obj2 = Integer.parseInt(temp[i]);
			localIP[i] = Obj2;
		}
	}

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SelectIP().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}
